### ISSUE TITLE
Text files are not generating.

### ISSUE THREAD

**Issue by ItsCEED** [TheAmadeus25/CounterStrike-GlobalOffensive-LiveStat-for-OBS-Studio#1]
No matter what I did or try, the text files are not they're not even reading the stats.

Every time I try to PING the server im getting an error.

**Comment by TheAmadeus25** [comment]
_First of all, I apologize that I'm writing many months later. I didn't got any notification from GitHub at all. Even using application which should give me a message on my phone didn't work. I didn't noticed this little "1" at all.... X.x_

Now to your problem (if you interested in it):

It seems that something has change inside GitHub at all. I'm pretty sure I uploaded a hotfix already before October but there still the outdated file here. _(I won't use GitHub desktop any more. So many bugs...)_

1. I uploaded the update for "**gamestate_integration_obs.cfg**" again.
2. **[Download](https://github.com/TheAmadeus25/CounterStrike-GlobalOffensive-LiveStat-for-OBS-Studio/tree/master/Sourcecode)** and Install the new file now. (**[Wiki](https://github.com/TheAmadeus25/CounterStrike-GlobalOffensive-LiveStat-for-OBS-Studio/wiki/Gamestate-Integration)**)
3. Start **CSGO** and **Node.js** again.
4. Check your console inside CSGO after starting. It should look like this one:

![Console](https://user-images.githubusercontent.com/12608333/72218669-cc97d080-353d-11ea-86e2-58b04d6bc1fe.png)

5. **Node.js** should look like here, while you're in the main menu of **CSGO**.

![AA](https://user-images.githubusercontent.com/12608333/72218877-4df06280-3540-11ea-8ae2-a7e9f0d92c82.PNG)

... and here while gaming

![BB](https://user-images.githubusercontent.com/12608333/72218921-ade70900-3540-11ea-83e6-46b4a1a58d09.PNG)


If it still doesn't generate any Textfiles, try to move the folder. For testing use this:

`C:\Test\`

I heard, that Microsoft add some security thing which isn't accessibly without rights, even it's the own script....

I hope it helped you. Can you answer me if it or not worked for you??
Have a nice Day

**Comment by ItsCEED** [comment]
Thank you, and no prob, i fixed it back in the days 🗡
